export const UIActionType = {
  NAVIGATE: 'NAVIGATE',
  PLAY_AUDIO: 'PLAY_AUDIO',
};

export const TriviasActionType = {
  FETCH_TRIVIAS: 'FETCH_TRIVIAS',
  RECEIVE_TRIVIAS: 'RECEIVE_TRIVIAS',
  RECEIVE_TRIVIA: 'RECEIVE_TRIVIA',
  VOTE_FOR: 'VOTE_FOR',
};

export const SnkrsActionType = {
  FETCH_SNKRS: 'FETCH_SNKRS',
  RECEIVE_SNKRS: 'RECEIVE_SNKRS',
};
